title: "Mon Wiki Homelab"
remote_theme: "pmarsceill/just-the-docs"
baseurl: "/admin-homelab"


# Permet les chemins simples (ex: /windows/)
permalink: pretty

# Active la recherche
just_the_docs:
  search_enabled: true
