title: "ðŸ§  Wiki SysAdmin â€“ CÃ©dric Ambos"
description: "Portfolio & Wiki Homelab"
remote-theme: "mminimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-search

# Layout par dÃ©faut pour toutes les pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      sidebar:
        nav: "navigation"

# Activer la recherche
search:
  enabled: true
  search_path: "/"                  
  search_input_placeholder: "Rechercher dans le wiki..."
