title: "Mon Wiki SysAdmin"
email: "cedric.ambos@gmail.com"
description: "Documentation SysAdmin Windows, Linux et Infrastructure"
url: "https://ced-0.github.io/admin-homelab"
baseurl: "/admin-homelab"

remote_theme: mminimal-mistakes-jekyll
minimal_mistakes_skin: "default"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-redirect-from

# Barre de recherche
search: true

# Affichage global
defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "wiki"

# Navigation sidebar
navigation:
  wiki:
    - title: "Accueil"
      url: /
    - title: "Ã€ propos"
      url: /about/

    - title: "Windows Server"
      children:
        - title: "Introduction"
          url: /windows/
        - title: "Active Directory"
          url: /windows/ad-ds/
        - title: "DNS"
          url: /windows/dns/
        - title: "DHCP"
          url: /windows/dhcp/
        - title: "Serveur de fichiers"
          url: /windows/filesrv/
        - title: "Serveur d'impression"
          url: /windows/printsrv/
        - title: "Collaboration"
          url: /windows/collaboration/

    - title: "Debian"
      children:
        - title: "Introduction"
          url: /debian/
        - title: "DNS"
          url: /debian/dns/
        - title: "DHCP"
          url: /debian/dhcp/
        - title: "Impression"
          url: /debian/print/

    - title: "Infrastructure"
      children:
        - title: "Vue d'ensemble"
          url: /infrastructure/
        - title: "pfSense"
          url: /infrastructure/pfsense/
        - title: "VLAN & Segmentation"
          url: /infrastructure/vlan-segmentation/
        - title: "GLPI"
          url: /infrastructure/glpi/
        - title: "Supervision"
          url: /infrastructure/supervision/
        - title: "RDS"
          url: /infrastructure/rds/
        - title: "WDS"
          url: /infrastructure/wds/

# GitHub
repository: "TON-USER/mon-wiki-sysadmin"

