title: "Mon Wiki Homelab"
remote_theme: "pmarsceill/just-the-docs"

# Permet des chemins simples (ex: /windows/)
permalink: pretty

# Active la recherche
just_the_docs:
  search_enabled: true

# Active Pygments pour la coloration syntaxique
highlighter: pygments  
