# _config.yml

title: "Mon Wiki Homelab"
remote_theme: "pmarsceill/just-the-docs"

# Navigation / Sidebar
nav:
  - title: Accueil
    url: /    

  - title: Introduction
    items:
      - title: Introduction AD DS
        url: /introduction/ad/
      - title: Introduction DNS
        url: /introduction/dns/
      - title: Introduction DHCP
        url: /introduction/dhcp/
      - title: Introduction serveur de fichier
        url: /introduction/fileserver/
      - title: Introduction serveur d'impression
        url: /introduction/printserver/

  - title: Windows
    items:
      - title: AD DS
        url: /windows/ad-ds/
      - title: DNS sur Windows server
        url: /windows/dns/        

  - title: Debian
    items:
      - title: DNS
        url: /debian/dns/        

  - title: Infrastructure
    items:
      - title: pfSense
        url: /infrastructure/pfsense/

