# _config.yml

title: "Mon Wiki Homelab"
remote_theme: "pmarsceill/just-the-docs"

# Navigation / Sidebar
nav:
  - title: Accueil
    url: /    
 - title: Introduction
    items:
      - title: AD
        url: /introduction/ad/
      - title: DNS
        url: /introduction/dns/
      - title: DHCP
        url: /introduction/dhcp/
      - title: File Server
        url: /introduction/fileserver/
      - title: Print Server
        url: /introduction/printserver/
      - title: Collaboration
        url: /introduction/collaboration/  
  - title: Windows
    items:
      - title: AD DS
        url: /windows/ad-ds/
      - title: DNS
        url: /windows/dns/        
  - title: Debian
        url: /debian/
      - title: DNS
        url: /debian/dns/        
  - title: Infrastructure
    items:
      - title: pfSense
        url: /infrastructure/pfsense/
