title: "Mon Wiki Homelab"
remote_theme: "pmarsceill/just-the-docs"

# Permet des chemins simples (ex: /windows/)
permalink: pretty

# Active la recherche
# Highlight.js pour la coloration des blocs de code
just_the_docs:
  search_enabled: true
  extra_head: "_includes/highlight-js.html"
